# Generated by Django 2.0.5 on 2018-06-04 12:33

from django.db import migrations

def load_stock_markets(apps, schema_editor):
    Stock = apps.get_model("stocks", "Stock")
    stock_amazon = Stock(id=0, name='AMZN')
    stock_amazon.save()
    stock_apple = Stock(id=1, name='AAPL')
    stock_apple.save()
    stock_microsoft = Stock(id=2, name='MSFT')
    stock_microsoft.save()
    stock_facebook = Stock(id=3, name='FB')
    stock_facebook.save()
    stock_jpmorgan = Stock(id=4, name='JPM')
    stock_jpmorgan.save()
    stock_intel = Stock(id=5, name='INTC')
    stock_intel.save()
    stock_cisco = Stock(id=6, name='CSCO')
    stock_cisco.save()
    stock_boeing = Stock(id=7, name='BA')
    stock_boeing.save()

def delete_stock_markets(apps, schema_editor):
    Stock = apps.get_model("stocks", "Stock")
    Stock.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20180602_1301'),
    ]

    operations = [
        migrations.RunPython(load_stock_markets, delete_stock_markets)
    ]
